version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:11.5
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    command: postgres -N 500

  api:
    container_name: api
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOSTNAME=postgres
    depends_on:
      - postgres